import random
from datetime import datetime
import logging
from ctf_gameserver import checkerlib
import uuid

LOCATIONS = ['Ancient Spires Outpost',
    'Dagger Tooth Outpost',
    "Galleon's Grave Outpost",
    'Golden Sands Outpost',
    "Morrow's Peak Outpost",
    'Plunder Outpost',
    'Sanctuary Outpost',
    "Brian's Bazaar",
    'Roaring Traders',
    "Stephen's Spoils",
    'The Finest Trading Post',
    'The North Star Seapost',
    'The Spoils of Plenty Store',
    'The Wild Treasures Store',
    'Three Paces East Seapost',
    'Barnacle Cay',
    'Black Sand Atoll',
    'Black Water Enclave',
    "Blind Man's Lagoon",
    'Booty Isle',
    'Boulder Cay',
    'Brimstone Rock',
    'Castaway Isle',
    'Chicken Isle',
    'Cinder Islet',
    'Cursewater Shores',
    'Cutlass Cay',
    "Flame's End",
    'Fools Lagoon',
    'Glowstone Cay',
    'Isle of Last Words',
    'Lagoon of Whispers',
    "Liar's Backbone",
    'Lonely Isle',
    'Lookout Point',
    "Magma's Tide",
    'Mutineer Rock',
    'Old Salts Atoll',
    'Paradise Spring',
    'Picaroon Palms',
    "Plunderer's Plight",
    'Rapier Cay',
    'Roaring Sands',
    'Rum Runner Isle',
    'Salty Sands',
    'Sandy Shallows',
    'Schored Pass',
    'Scurvy Isley',
    "Sea Dog's Rest",
    'Shark Tooth Key',
    'Shiver Retreat',
    'The Forsaken Brink',
    'Tribute Peak',
    'Tri-Rock Isle',
    'Twin Groves',
    'Ashen Reaches',
    'Cannon Cove',
    'Crescent Isle',
    "Crook's Hollow",
    "Devil's Ridge",
    'Discovery Ridge',
    "Fetcher's Rest",
    'Flintlock Peninsula',
    "Kraken's Fall",
    'Lone Cove',
    "Marauder's Arch",
    "Mermaid's Hideaway",
    'Old Faithful Isle',
    'Plunder Valley',
    "Ruby's Fall",
    "Sailor's Bounty",
    'Shark Bait Cove',
    'Shipwreck Bay',
    "Smugglers' Bay",
    'Snake Island',
    'The Crooked Masts',
    "The Devil's Thirst",
    'The Sunken Grove',
    "Thieves' Haven",
    'Wanderers Refuge',
    'Hidden Spring Keep',
    'Keel Haul Fort',
    'Kraken Watchtower',
    'Lost Gold Fort',
    'Molten Sands Fortress',
    'Old Boot Fort',
    "Sailor's Knot Stronghold",
    'Shark Fin Camp',
    'Skull Keep',
    "The Crow's Nest Fortress"]

PIRATES = ['Cap’n Dreadful',
 'Captain Justeene',
 'Captain Seadog',
 'Captain Mack Calabran',
 'Captain Vex Totem',
 'Captain Black Jack',
 'Captain Blackbeard',
 'Captain Silver-Tongue',
 'Captain Silver-Hook',
 'Admiral Davey',
 'Admiral Williams',
 'Captain Jolly',
 'Captain O’Fish',
 'Admiral Storm',
 'Captain Booty',
 'Captain Crabby',
 'Captain Redbeard',
 'Captain Puffypants',
 'Captain Cannon',
 'Admiral Spike',
 'Admiral Wade',
 'Captain Lazyjacks',
 'Admiral Mullins',
 'Captain Rattlebones',
 'Cap’n Skully',
 'Captain Crawford',
 'Sir John Winters',
 'Captain Vera Brave',
 'Captain Liza Scallywag',
 'Captain Cecila Jagger',
 'Admiral Hawk',
 'Captain Drake Deranged',
 'Captain Slyvester Shadows',
 'Admiral Simpson',
 'Captain Deepsea Davey',
 'Captain David Death',
 'Captain Mildred McCoy',
 'Captain Rivers McGee',
 'Captain Julie Jagger',
 'Captain Patty Price',
 'Captain McKraken',
 'Captain Van Horne',
 'Captain Sandy Shores',
 'Captain McFilthy',
 'Captain Scurvyshorts',
 'Captain Randell Red-Lord',
 'Captain Fish-Lips',
 'Admiral Henry Heart',
 'Captain Renshaw Vance',
 'Captain Eldar Nightwind',
 'Cap’n Chipper Toes',
 'Pete Blackbeard',
 'Bill Bones',
 'Peteplank',
 'Black Bill The Feared',
 'Wainwright ‘Bird Eye’ Shelley',
 'John Blackeye',
 'Poopdeck Pete',
 'Big Jones',
 'Maximus Dark-Skull',
 'Toothless Pete',
 'Crimson Seadog',
 'Musclemouth Mike',
 'Winter Greybeard',
 'Chipper Goldheart',
 'Thunder Dave',
 'Stinkin’ Pete',
 'Davey Dark-Skull',
 'Old-Tide Sammy',
 'Pistol-Grin Gary',
 'Old Chipper',
 'One-Tooth John',
 'Hunter Brendan',
 'Speechless Mike',
 'Mad Michael',
 'Handsome Jimmy',
 'Rascal Jimmy',
 'Cannonball Conner',
 'Jason Sea Legs',
 'Barnacle Bill',
 'Silver-Tooth Samuel',
 'Pete Peg-Leg',
 'Lazy-Eye Louie',
 'Paddy Sparrow',
 'Vince Puffypants',
 'Jack Red-Locks',
 'Gordon Rough',
 'Oscar Foul',
 'Wyatt Gold',
 'Edwin ‘No Money’ Mables',
 'Theo Stinkalot',
 'George Balding',
 'Hansel The Handsome',
 'Jonas Rattler',
 'Jacob Cutter',
 'Wade Wilds',
 'Randell Rummy',
 'Garrick Roach',
 'Malvo Razor-Face',
 'Roger Starky',
 'Finn O’Fish',
 'Dirty Danny',
 'Churchhill Evans',
 'Celia ‘Butcher’ Tyde',
 'Elnora ‘Evil Grin’ Neale',
 'Shiverin’ Shelley',
 'Mighty Mary',
 'Kellie Strong-Heart',
 'Misty Winters',
 'Voodoo Wendy',
 'Salty Sarah',
 'Shark-Fin Suzie',
 'Penelope Precious',
 'Sugar-Tongue Shelly',
 'Silvera Snake-Eyes',
 'Boney Brenda',
 'One-Leg Nellie',
 'One-Eye Wendy',
 'Lady Tide',
 'Cut-Throat Connie',
 'Nancy Tall-Tide',
 'Moonie Two-Toe',
 'Esme Dark-Waters',
 'Jilly Buckets',
 'Mary Gun-Powder',
 'Liza Mcgee',
 'Sadie Waters',
 'Joy McStubby',
 'Betty Tuna-Breath',
 'Opal Sea-Wolf',
 'Nancy Lobster-Legs',
 'Bella O’Greed',
 'Ella Treasures',
 'Ruth O’Patches',
 'Miranda Gold-Tooth',
 'Vera Sparrow',
 'Carrie Atlantis',
 'Mazie Deep-Waters',
 'Peggy One-Leg',
 'Evie Shark-Bait',
 'Lou-Lou Stubbs',
 'Polly d’Plank',
 'Pearl Bailey',
 'Glory Jones',
 'Clara Shadows',
 'Sally Black',
 'Daisy O’Jelly',
 'Suzie McGraw',
 'Janie Big-Lips',
 'Vicky FishMonger',
 'Mabel Hook-Hand',
 'Mae Whiskey-Woo',
 'Martha One-Eyed',
 'Crazy Kellie',
 'Lady Cassandra',
 'Lady Marilyn Man-Eater']

LOREM_IPSUM = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."

def random_loc():
    return random.choice(LOCATIONS)

def random_name():
    return random.choice(PIRATES) + str(random.randint(10000, 99999))

def random_date():
    timestamp = random.randrange(1623448800, 1640905200)
    dt_object = datetime.fromtimestamp(timestamp)
    return str(dt_object)

def random_lorem_ipsum():
    r = random.randint(3, 50)
    res = random.choices(LOREM_IPSUM.split(), k=r)
    return " ".join(res)

def random_pin():
    return str(random.randint(1000000000, 9999999999))

def log_error_and_quit(res, msg):
    logging.error(f"URL: {res.request.method} {res.request.url} - {msg}")
    return None

def check_uuid(id):
    try:
        uuid.UUID(id)
    except:
        return None
    return id
